services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8446132964:AAHI0HN0cHH9Y1m8ktkHWYoDqoUe6iGb2LI  # У лапках
      - key: ADMIN_ID
        value: 984209612  # У лапках, але буде перетворено в int
