services:
  - type: web
    name: telegram-bot
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:wsgi_app
    envVars:
      - key: BOT_TOKEN
        value: ваш_токен
      - key: ADMIN_ID
        value: ваш_id
